<<<<<<< HEAD
# Generated by Django 5.2 on 2025-05-17 12:23
=======
# Generated by Django 5.2 on 2025-05-15 08:53
>>>>>>> 7065014f6ba19135e4a15716eb87ce3569946d8e

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
<<<<<<< HEAD
                ('my_order', models.PositiveIntegerField(blank=True, default=0, null=True)),
=======
>>>>>>> 7065014f6ba19135e4a15716eb87ce3569946d8e
                ('title', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
<<<<<<< HEAD
                'db_table': 'category',
                'ordering': ['my_order'],
=======
>>>>>>> 7065014f6ba19135e4a15716eb87ce3569946d8e
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
<<<<<<< HEAD
                ('my_order', models.PositiveIntegerField(blank=True, default=0, null=True)),
=======
>>>>>>> 7065014f6ba19135e4a15716eb87ce3569946d8e
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='products/')),
                ('discount', models.PositiveIntegerField(default=0)),
                ('amount', models.PositiveIntegerField(default=1)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
<<<<<<< HEAD
                'db_table': 'product',
                'ordering': ['my_order'],
=======
                'ordering': ['-price'],
>>>>>>> 7065014f6ba19135e4a15716eb87ce3569946d8e
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
<<<<<<< HEAD
                ('my_order', models.PositiveIntegerField(blank=True, default=0, null=True)),
=======
>>>>>>> 7065014f6ba19135e4a15716eb87ce3569946d8e
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shop.product')),
            ],
            options={
<<<<<<< HEAD
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('my_order', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('content', models.TextField()),
                ('rating', models.IntegerField(choices=[(0, 'Zero'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=3)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shop.product')),
            ],
            options={
                'db_table': 'comment',
=======
                'abstract': False,
>>>>>>> 7065014f6ba19135e4a15716eb87ce3569946d8e
            },
        ),
    ]
